Fix the bug in BlitzWho and adapt BlitzFirst table
BrentOzarULTD/SQL-Server-First-Responder-Kit pull request #2567
Opened 2020-09-06 10:19 UTC by AdrianB1

2020-09-08 13:43 UTC, BrentOzar requested changes
Not sure if you meant to check in both sp_BlitzFirst and sp_BlitzWho. Can you give me a quick rundown of why you did what you did, and whether it'll break other things, like how sp_BlitzFirst calls sp_BlitzCache? I think I might not have understood something. Thanks!

2020-09-08 13:43 UTC, BrentOzar commented on sp_BlitzFirst.sql
> +	DECLARE	@v DECIMAL(6,2),
Why did we take the ReadableDBs population line out of this section? We do need it for sp_BlitzCache I think, based on a quick code review. I'm guessing you wanted to use it down in the sp_BlitzWho section maybe, or maybe you didn't mean to include this file in your pull request? Let me know either way.

2020-09-08 13:43 UTC, BrentOzar commented on sp_BlitzWho.sql
> +IF OBJECT_ID('tempdb..#ReadableDBs') IS NOT NULL
If we're populating a list of ReadableDBs in here, why do we need to make any changes in sp_BlitzFirst?

2020-09-16 12:46 UTC, AdrianB1 commented
The implementation of sp_BlitzWho is identical with sp_BlitzCache; a local ReadableDBs is needed in each to be able to run independently when needed.

But with this change an error appears in sp_BlitzFirst:  (Message 50000)  Invalid object name '#ReadableDBs'. Moving the creation of ReadableDB's in sp_BlitzFirst after calling sp_BlitzWho is solving the problem. I did not figure yet why this temp table is reported missing after sp_BlitzWho runs, I will continue to investigate that.

2020-09-16 12:48 UTC, BrentOzar commented
Okay, if you change sp_BlitzFirst, make sure sp_BlitzCache still runs appropriately. My guess is that the change you made to sp_BlitzFirst may break sp_BlitzCache's functionality on readable secondaries.

I'm going to go ahead and close this, but give 'er another shot when you're ready. Thanks!

2020-09-16 12:48 UTC, closed without merging