sp_AllNightLog - Error handling improvements
BrentOzarULTD/SQL-Server-First-Responder-Kit pull request #3207
Opened 2023-01-06 14:58 UTC by DavidWiseman

## Summary 

* Fix error handling
* Add check for CommandLog table
* Change Processing order to prevent DBs with an error condition from monopolizing the queue 
* Moved job enabled check to end of loop - faster & more reliable shutdown. 
* Removed @error_number IS NOT NULL check.  We are in the catch block so an error has occurred and an error number is expected.  

#3203

## Restore Example:
Add this to the top of sp_DatabaseRestore:
```sql
RAISERROR('Fatal error',16,1)
```

New version shows the error details for easy troubleshooting.  We also exit after we process the first DB from the queue with the jobs disabled - rather than wait for the queue to empty.  With the error now been caught the DB ends up back in the queue so we would never shutdown if there is an error condition without also including this change.  

With the old version it's not clear that an error occurred.  We also process each item in the queue until the queue is empty so we are looping more times (potentially resulting in slow/unreliable shutdown).  

As the error handling is now working, an error condition causes the DB to be put back in the queue for immediate re-processing.  The ordering has been changed so it won't always be the first DB to be pulled off the queue (preventing other DBs from processing if there is an error condition on 1 DB).

![image](https://user-images.githubusercontent.com/33157668/211029141-43a9e098-1408-4d56-904f-191ccc5bdc20.png)

## Backup example:
Add this to dbo.DatabaseBackup:
RAISERROR('fatal error 123',16,1)

Similar to the restore fix, we can now see the error where there was no error indication with the old version.
![image](https://user-images.githubusercontent.com/33157668/211032382-8f9d252d-2ab1-4bd4-9827-2071e4a36eee.png)

If the CommandLog table is missing we now bail out early with a friendly error message:
![image](https://user-images.githubusercontent.com/33157668/211033207-a3224ab4-07dc-4c15-976d-ff006cc23e62.png)

2023-01-06 15:01 UTC, BrentOzar requested changes
Thanks for the pull request. There are changes in here that I don't quite understand - I'm guessing maybe you removed code you didn't want to, or tried reformatting the code. If you look at the pull request page here, the old code is on the left, and the changed code is on the right: https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/pull/3207/files

If you didn't mean to make all these changes, can you remove the parts you didn't mean to make? For example, on the left in the original code circa line 892, an entire query has been deleted with no explanation. Around lines 1016-1020, I can't tell what we changed, or why.

2023-01-06 15:32 UTC, DavidWiseman reviewed
Added comments to help make review easier.

2023-01-06 15:32 UTC, DavidWiseman commented on sp_AllNightLog.sql
> -						                    FROM msdb.dbo.sysjobs
This was moved to line 1066.  The check is now done at the end of the loop - so we process 1 database and perform this check, rather than wait for the queue to be empty (database is NULL).  The problem with waiting for the queue to be empty is that this will never occur if there is an error condition as the DB gets added back to the queue for immediate processing.

2023-01-06 15:32 UTC, DavidWiseman commented on sp_AllNightLog.sql
> -
This was moved to line 1507.  The check is now done at the end of the loop - so we process 1 database and perform this check, rather than wait for the queue to be empty (database is NULL).  The problem with waiting for the queue to be empty is that this will never occur if there is an error condition as the DB gets added back to the queue for immediate processing.

2023-01-06 15:32 UTC, DavidWiseman commented on sp_AllNightLog.sql
> +IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'CommandLog')
Added check to bail out early if CommandLog table doesn't exist

2023-01-06 15:32 UTC, DavidWiseman commented on sp_AllNightLog.sql
> +										/*
As the error handling is now working, an error condition causes the DB to be put back in the queue for immediate re-processing. The ordering has been changed so it won't always be the first DB to be pulled off the queue (preventing other DBs from processing if there is an error condition on 1 DB).

2023-01-06 15:32 UTC, DavidWiseman commented on sp_AllNightLog.sql
> +										/*
As the error handling is now working, an error condition causes the DB to be put back in the queue for immediate re-processing. The ordering has been changed so it won't always be the first DB to be pulled off the queue (preventing other DBs from processing if there is an error condition on 1 DB).

2023-01-06 15:32 UTC, DavidWiseman commented on sp_AllNightLog.sql
> -
This should be done in the CATCH block.  If an error occurs this code wouldn't get executed.

2023-01-06 15:32 UTC, DavidWiseman commented on sp_AllNightLog.sql
> +						*/
Provide a detailed error, preserving as much of the original error information as possible to assist troubleshooing

2023-01-06 15:32 UTC, DavidWiseman commented on sp_AllNightLog.sql
> +						SELECT @error_number = ERROR_NUMBER(),
This is where we need to set error_number

2023-01-06 15:32 UTC, DavidWiseman commented on sp_AllNightLog.sql
> -						IF  @error_number IS NOT NULL
Removed IS NOT NULL check.  We are in the catch block so an error number is expected.  Previously the error_number was NULL as it wasn't set in the CATCH block.

2023-01-06 15:32 UTC, DavidWiseman commented on sp_AllNightLog.sql
> +					/* Check to make sure job is still enabled */
This was moved here. The check is now done at the end of the loop - so we process 1 database and perform this check, rather than wait for the queue to be empty (database is NULL). The problem with waiting for the queue to be empty is that this will never occur if there is an error condition as the DB gets added back to the queue for immediate processing.

2023-01-06 15:32 UTC, DavidWiseman commented on sp_AllNightLog.sql
> -
This should be done in the CATCH block. If an error occurs this code wouldn't get executed.

2023-01-06 15:32 UTC, DavidWiseman commented on sp_AllNightLog.sql
> -						IF  @error_number IS NOT NULL
Removed IS NOT NULL check. We are in the catch block so an error number is expected. Previously the error_number was NULL as it wasn't set in the CATCH block.

2023-01-06 15:32 UTC, DavidWiseman commented on sp_AllNightLog.sql
> +						*/
Provide a detailed error, preserving as much of the original error information as possible to assist troubleshooing

2023-01-06 15:32 UTC, DavidWiseman commented on sp_AllNightLog.sql
> +						SELECT @error_number = ERROR_NUMBER(),
Moved to CATCH block

2023-01-06 15:32 UTC, DavidWiseman commented on sp_AllNightLog.sql
> +							        SET @msg = N'Updating restore_worker for database ' + ISNULL(@database, 'UH OH NULL @database') + ' for successful restore';
typo

2023-01-06 15:32 UTC, DavidWiseman commented on sp_AllNightLog.sql
> +							        SET @msg = N'Updating restore_worker for database ' + ISNULL(@database, 'UH OH NULL @database') + ' for UNsuccessful restore';
typo

2023-01-06 15:32 UTC, DavidWiseman commented on sp_AllNightLog.sql
> +						END; -- End update for successful restore
This was moved here. The check is now done at the end of the loop - so we process 1 database and perform this check, rather than wait for the queue to be empty (database is NULL). The problem with waiting for the queue to be empty is that this will never occur if there is an error condition as the DB gets added back to the queue for immediate processing.

2023-01-06 15:32 UTC, DavidWiseman commented on sp_AllNightLog.sql
> -							BEGIN
BEGIN/END removed along with associated TAB spaces.  (See Removed IS NOT NULL comment above)

2023-01-06 15:32 UTC, DavidWiseman commented on sp_AllNightLog.sql
> -							BEGIN
BEGIN/END removed along with associated TAB spaces (See Removed IS NOT NULL comment above)

2023-01-29 20:54 UTC, DavidWiseman commented
I've added comments to all the code changes, but just to clarify - the changes are all intentional.  If you need anything else from me, please let me know.

2023-12-12 15:23 UTC, BrentOzar commented
So, this is a tough one: it's been open for almost a year, and no one else has been able to do the code review due to the number of changes. I'm going to go ahead and close this, but going forward, when you contribute code to open source projects, here are a few tips to maximize your chance of getting the pull request accepted:
* Make one issue for each problem you're trying to solve
* Include a repro script that someone else can run on their machine in order to see the issue - [here's an example of a repro script](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/issues/3405#issuecomment-1847595377)
* Make one pull request for each issue, max (don't try to solve multiple problems in one pull request)

That way, someone can copy/paste your repro script, see the exact error or problem that you're trying to solve, and then run the repro script again with your changes, and see that it's fixed.

Otherwise, the way it is here, I don't know if this PR made things better or worse. I really wish I had the time to dig into pull requests like this, believe me, but only so many hours in each day.

2023-12-12 15:23 UTC, closed without merging

2023-12-12 16:31 UTC, DavidWiseman commented
Thanks for the response - I'm happy for this to be killed off.  I normally prefer to do smaller PRs when contributing to other projects but this required some more substantial restructuring to fix the broken error handling.  I appreciate this made it hard to review.  

I think the overall principle behind sp_AllNightLog is good but it has a number of issues.  I ended up writing a console app as a replacement as I needed something that could do the same thing but also work from backups to Azure blob.

2023-12-12 16:32 UTC, BrentOzar commented
@DavidWiseman yeah, totally understand. I've worked with a couple of clients who started with sp_AllNightLog, and then gradually wanted something more powerful and flexible, and then built complex applications to do it.