sp_Blitz: Added check for Query Store not being in READ_WRITE state and check for it not being in desired state.
BrentOzarULTD/SQL-Server-First-Responder-Kit pull request #3536
Opened 2024-06-15 20:35 UTC by ReeceGoding

Closes item 5 in https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/issues/3527 . Only item 6 is now awaiting a PR. This change includes two new checks. Adding a check for Query Store not being in its desired state was such a natural follow-up from checking for READ_WRITE that I couldn't resist.

I've made this a priority 200 issue under the 'Performance' header. This is the consistent with the check for having Query Store completely disabled. After all, these two issues effectively disable Query Store.

The URL I've added is the best one that I know for this topic. Both checks have the same URL.

I've only been able to test the check for the READ_WRITE state. I've only ever seen Query Store leave its desired state on busy production databases. I'm unsure how to simulate it to test it myself. I'm open to ideas. Maybe just make the settings for Query Store ridiculously low and hit your server very hard?

2024-06-20 15:56 UTC, BrentOzar commented on sp_Blitz.sql
> +		                              SELECT TOP 1 262,
In another pull request, you're using 262 as the ID for a different check. Can you fix the check numbers in this and the documentation, and then I can accept it? Thanks!

2024-06-20 15:56 UTC, BrentOzar requested changes
In another pull request, you're using 262 as the ID for a different check. Can you fix the check numbers in this and the documentation, and then I can accept it? Thanks!

2024-06-20 19:01 UTC, ReeceGoding commented
@BrentOzar That should fix it.

2024-06-22 13:02 UTC, ReeceGoding commented
>  I'm unsure how to simulate it to test it myself. I'm open to ideas. Maybe just make the settings for Query Store ridiculously low and hit your server very hard?

Tested this. It worked. You don't even have to hit the server hard. Just make the Query Store settings super low.

2024-06-30 14:13 UTC, BrentOzar approved these changes
Thanks for the PR! Looks good, and thanks for doing the documentation changes too. Makes sense, merging into the dev branch. I'm doing a July release a little early to get a couple of fixes into the Consultant Toolkit, and this will be in there.

2024-06-30 14:13 UTC, merged